### ISSUE TITLE
Use html.erb rather than html.slim

### ISSUE THREAD

**Issue by MikeMcQuaid** [koraktor/braumeister.org#51]
I've contributed to a few open source projects using Rails and this is the first one I've seen using html.slim files. I'm of the opinion if you've never used them before they make it significantly harder for new contributors to get running.

Could use something like https://stackoverflow.com/questions/23277482/how-can-i-convert-html-slim-to-html-erb to convert these files.

**Comment by koraktor** [comment]
I’m ambivalent about this.

I introduced Slim (which hasn‘t been that long, d60ad71ef78c63a66a0ecec37fe8c435285f525d) because of its concise syntax and the ability to write really clean templates.
But I fully understand your point about it raising the entry hurdle for new contributors. Especially the whitespace handling is a problem. (I even thought about creating some sort of simple whitespace mode for Slim. 😆)

ERB on the other hand is a piggybacking template engine (i.e. you still write HTML etc.) which I find unnecessarily hard to read for complex templates. And ERB’s tags `<% %>` even add to this.

I’m still open for this. But just switching back to ERB (`git revert d60ad71`) doesn’t feel right IMHO.

**Comment by MikeMcQuaid** [comment]
> But I fully understand your point about it raising the entry hurdle for new contributors.
> ERB on the other hand is a piggybacking template engine (i.e. you still write HTML etc.) which I find unnecessarily hard to read for complex templates. And ERB’s tags <% %> even add to this.

I see this as a feature rather than a bug. If you have a contributor who wishes to make an HTML/design change then they can pretty much ignore the ERB and just ignore the HTML. Ultimately: you're generating HTML here so the learning curve for people with experience of neither is higher with Slim (and HAML, etc.) than with ERB.

Ultimately the Rails ecosystem has tried a few of these things over the years (even for JavaScript generation) and ended up back with ERB because it's the easiest to read and debug. I think it's worth sticking with ERB for this reason alone for an open-source project that wants contributors.
